### ISSUE TITLE
nomad.client.allocs.oom_killed missing from metrics endpoint

### ISSUE THREAD

**Issue by netdata-be** [hashicorp/nomad#10155]
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Centos 8

### Issue
Missing nomad.client.allocs.oom_killed from the metrics endpoint

### Reproduction steps

* Enable prometheus metrics
* Curl the metrics endpoint <ipaddress>:4646/v1/metrics?format=prometheus

#### Expected Result

Return the metric with count and lables as documented

**Comment by jrasell** [comment]
Hi @netdata-be, do you have examples of tasks which have been terminated because of OOM? If not, it could be the case that the metric has never been incremented and therefore is not within the metrics memory store to return to the scraper.

**Comment by pznamensky** [comment]
See also: https://github.com/hashicorp/nomad/issues/4449

**Comment by rkettelerij** [comment]
Indeed this is already reported in #4449. The problem is that the OOM metric in Nomad doesn't have an initial value. This doesn't fit 'the Prometheus way', metrics should always be present even if their initial value is 0. I think it's best to fix this on the Nomad side.

Meanwhile I've implemented a workaround to alert on the OOM metric. My alert is as follows:

```
      - alert: NomadKilledTaskDueToOOM
        expr: sum by(node) (nomad_client_allocs_oom_killed or vector(0))>=1 # the tricky part is that nomad_client_allocs_oom_killed has no initial value, therefore we need vector(0).
        labels:
          severity: critical
        annotations:
          description: "Nomad killed one allocation on node {{ $labels.node }} due to OutOfMemory. Nomad will restart the task automatically."
          summary: "Nomad killed one allocation on node {{ $labels.node }} due to OutOfMemory"
```
