### ISSUE TITLE
grafana Dashboard

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#10162]
Hello Nomad Community,

It's nice to use nomad. We wanted to see if we have an available nomad grafana dashboard Which can show all-important metrics.

**Comment by thatsk** [comment]
https://grafana.com/grafana/dashboards/6278 this is not working as expected with the latest version of nomad

**Comment by notnoop** [comment]
@thatsk Thanks for raising this.  To help us dig into the issue, can you also provide a more detailed description of the issue?  A screenshot of the dashboards before and after, ideally the metrics info, and how it doesn't match expectation will be great.

**Comment by thatsk** [comment]
![image](https://user-images.githubusercontent.com/15324013/111592496-de829c80-87ee-11eb-815a-e5d4659d32b2.png)

Prometheus Rule:-
{code}
- job_name: nomad_metrics
  params:
    format:
    - prometheus
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /v1/metrics
  scheme: http
  consul_sd_configs:
  - server: localhost:8500
    token: "%{alias('consul.mobi_service_token')}"
    datacenter: dev
    scheme: http
    services:
    - nomad-client
    - nomad
  relabel_configs:
  - source_labels: ['__meta_consul_tags']
    regex: (.*)http(.*)
    action: keep
{code}

**Comment by thatsk** [comment]
in host tab it should all nomad client host and graphs should be created accordingly. Might be our exporter information has changed and that's why its failing ?

**Comment by thatsk** [comment]
Thanks @tgross let me know if i can help anything in this.

**Comment by tgross** [comment]
@thatsk just for clarity, that dashboard is from a third-party and not from HashiCorp. It looks like its source is at https://github.com/dereknex/nomad-grafana but you'll note that its last commits were >3 years ago and the repo has been archived by its owner. That means it's probably using the metrics we were shipping before 0.8. If you want to update your dashboard, you might want to look at https://www.nomadproject.io/docs/operations/metrics to get a current set of metrics.

I'm going to mark this as an enhancement because it would be nice if our ecosystem folks could work on something like this. But you might also get good results by opening a conversation on [Discuss](https://discuss.hashicorp.com/c/nomad/28) to see if anyone in the community has a good dashboard.

**Comment by nahsi** [comment]
@thatsk
I've made a dashboard for Nomad recently, it is work in progress but please have a look
https://grafana.com/grafana/dashboards/15764

**Comment by thatsk** [comment]
this looks awesome @nahsi  but while I am importing getting errors on some of the data. can you tell me which version of grafana you are using?

**Comment by thatsk** [comment]
@nahsi 
```
  nomad:
    service:
      id: "nomad-api"
      name: "nomad-api"
      port: 4646
      tags:
        - "ingress.enable=true"
        - "ingress.http.routers.nomad.entrypoints=https"
        - "ingress.http.routers.nomad.rule=Host(`redacted`)"
      meta:
        external-source: "consul"
      check:
        id: "nomad-api-health"
        name: "nomad-api-health"
        http: "http://localhost:4646/v1/agent/health"
        interval: "20s"
        timeout: "2s"
```
is this nomad-client service which is registered in consul . i just confused is this nomad job or nomad service

**Comment by nahsi** [comment]
@thatsk this is how I register nomad clients and servers with https://www.consul.io/docs/discovery/services so I can scrape them also for discovery by traefik.

It is in yaml because it is in ansible inventory (copy it to host with Ansible filter `to_nice_json`)

**Comment by thatsk** [comment]
got it thanks for the info. I am gonna try this now with grafana 8.6.3 & Prometheus as datasource.

**Comment by thatsk** [comment]
@nahsi 
https://gist.github.com/thatsk/62a6da944ff73244a76f64d413504f48#file-nomadgrafana-json-L427
https://gist.github.com/thatsk/62a6da944ff73244a76f64d413504f48#file-nomadgrafana-json-L2286

Can you update this? it's actually pointing wrong destination.

**Comment by thatsk** [comment]
what is the system dashboard when I click on any node? and env variable is not showing any data is there any issue on that.

**Comment by thatsk** [comment]
![image](https://user-images.githubusercontent.com/15324013/154927220-8d8663db-3e06-4ec9-8b1c-2c32c234b3cb.png)

**Comment by thatsk** [comment]
@nahsi let me know if i need to change anything

**Comment by thatsk** [comment]
some of tabs are not showing data is that due to env variable

**Comment by nahsi** [comment]
@thatsk `env` is what we use at the place I work in
We add it on metrics collection agent level
For example vmagent/prometheus config:
```yaml
global:
  scrape_interval: "30s"
  external_labels:
    env: '{{ env "node.datacenter" }}'

``` 
Or better yet register nomad with meta `env=<your_env>` then scrape with:
```yml
  - job_name: "nomad"
    metrics_path: "/v1/metrics"
    params:
      format: ["prometheus"]
    consul_sd_configs:
      - server: "http://172.26.64.1:8500"
        services:
          - "nomad-api"
    relabel_configs:
      - source_labels: ["__meta_consul_node"]
        target_label: "instance"
      - source_labels: ["__meta_consul_service_metadata_env"]
        target_label: "env"
```

Also I think this issue is not a good place for this sort of discussions :) Let's continue someplace else? Please write me at [telegram](https://t.me/nahsi_at_tg) or [mail](mailto:nahsi@nahsi.dev) me if you have any questions
