### ISSUE TITLE
docker drive can't support env name have point

### ISSUE THREAD

**Issue by lialzm** [hashicorp/nomad#11027]
this my docker compose config,It's work

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es7_01
    environment:
      - cluster.name=zjc-es-cluster
      - node.name=es7_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es7_01
```

but in nomad, i use env,It's not work

```
      env {
        cluster.name = "es7_01"
        node.name = "node1"
        bootstrap.memory_lock=true
        ES_JAVA_OPTS="-Xms512m -Xmx512m"
        discovery.seed_hosts="es7_01"
      }

```

I get error like

```
Argument or block definition required; An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```
