### ISSUE TITLE
Can the volumes be declared in group?

### ISSUE THREAD

**Issue by lialzm** [hashicorp/nomad#11551]
I just know config host volume in  nomad client , can it be declared in the group like k8s?

```
  volumes:
    - name: flink-volume-hostpath
      hostPath:
        path: /tmp
        type: Directory
    - name: flink-artifact
      emptyDir: { }
    - name: flink-logs
      emptyDir: { }

```
