### ISSUE TITLE
System jobs could not recover after abrupt node restart.

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/nomad#14932]
### Nomad version
1.4.1

### Operating system and Environment details
Ubuntu

### Issue
Some nomad system jobs not recovering after node is lost and reconnected. I should also mention that some work well as expected.

### Reproduction steps
Run a 1-server, 2-client setup and run a system job like traefik. Now abruptly shutdown the system (power-failure) and restart. The system job now only runs on 1 (or 0) clients.

#### Expected Result
Nomad should recover and run system job on all nodes.

#### Actual Result
The job runs only one some/no clients.

### Job file (if appropriate)
```yaml
ID: caddy
Name: caddy
Type: system
Priority: 90
Region: "home"
Datacenters: [ "dc_name" ]
TaskGroups:
- Name: caddy
  Tasks:
  - Name: caddy
    Driver: docker
    Config:
      image: blmhemu/caddy:latest # Custom docker image built weekly https://github.com/blmhemu/caddy-docker
      ports: [ http, https, ts_http, ts_https, health ]
      volumes: [ "local:/etc/caddy" ]
    Resources:
      CPU: 500
      MemoryMB: 256
    Templates:
    - DestPath: "${NOMAD_SECRETS_DIR}/env.vars"
      LeftDelim: "[["
      RightDelim: "]]"
      ChangeMode: "restart"
      Envvars: true
      EmbeddedTmpl: |
        [[- range nomadVarList ]]
          [[- with nomadVar .Path ]]
            [[- range .Tuples ]]
        [[ .K ]]="[[ .V ]]"
            [[- end ]]
          [[- end ]]
        [[- end ]]
    - DestPath: "${NOMAD_TASK_DIR}/Caddyfile"
      ChangeMode: "script"
      ChangeScript:
        Command: "/usr/bin/caddy"
        Args: [ "reload", "--config", "/etc/caddy/Caddyfile" ]
      LeftDelim: "[["
      RightDelim: "]]"
      EmbeddedTmpl: |
        {
            storage consul {
                address      "consul-api.service.consul:8500"
                timeout      10
                prefix       "caddytls"
                aes_key      {$CONSUL_AES_KEY}
                tls_enabled  "false"
                tls_insecure "true"
            }

            servers {
                metrics
            }
        }

        :{$NOMAD_PORT_health} {
            respond /health "OK" 200
            metrics /metrics
        }

        *.{$BASE_DOMAIN} {
            tls {
                dns cloudflare {$CF_TOKEN}
                resolvers 1.1.1.1
            }

            [[- define "simple_reverse_proxy" ]]
            [[- if (service .) ]]
            @[[ . ]] host [[ . ]].{$BASE_DOMAIN}
            handle @[[ . ]] {
                reverse_proxy [[- range service . ]] [[ .Address ]]:[[ .Port ]] [[- end ]]
            }
            [[- end ]]
            [[- end ]]

            [[- range (sprig_list "echo" "victoriametrics" "grafana") ]]
            [[ template "simple_reverse_proxy" . ]]
            [[- end ]]

            [[- if (service "nomad-api") ]]
            @nomad-api host nomad-api.{$BASE_DOMAIN}
            handle @nomad-api {
                basicauth {
                    {$NOMAD_AUTH_USER} {$NOMAD_AUTH_PASS}
                }
                reverse_proxy [[- range service "nomad-api" ]] [[ .Address ]]:[[ .Port ]] [[- end ]]
            }
            [[- end ]]

            [[- if (service "consul-api") ]]
            @consul-api host consul-api.{$BASE_DOMAIN}
            handle @consul-api {
                basicauth {
                    {$CONSUL_AUTH_USER} {$CONSUL_AUTH_PASS}
                }
                reverse_proxy [[- range service "consul-api" ]] [[ .Address ]]:[[ .Port ]] [[- end ]]
            }
            [[- end ]]

            [[- if (service "nextcloud") ]]
            @nextcloud host nextcloud.{$BASE_DOMAIN}
            handle @nextcloud {
                redir /.well-known/carddav /remote.php/dav 301
                redir /.well-known/caldav /remote.php/dav 301
                header Strict-Transport-Security "max-age=15552000; includeSubDomains"
                reverse_proxy [[- range service "nextcloud" ]] [[ .Address ]]:[[ .Port ]] [[- end ]]
            }
            [[- end ]]

            handle {
                abort
            }
        }

  - Name: cloudflared
    Driver: docker
    Config:
      image: cloudflare/cloudflared:latest
      command: tunnel
      args: ["run"]
    Templates:
    - DestPath: "${NOMAD_SECRETS_DIR}/env.vars"
      LeftDelim: "[["
      RightDelim: "]]"
      ChangeMode: "restart"
      Envvars: true
      EmbeddedTmpl: |
        [[- range nomadVarList ]]
          [[- with nomadVar .Path ]]
            [[- range .Tuples ]]
        [[ .K ]]="[[ .V ]]"
            [[- end ]]
          [[- end ]]
        [[- end ]]
    Resources:
      CPU: 500
      MemoryMB: 128

  Networks:
  - Mode: bridge
    ReservedPorts:
    - Label: http
      Value: 80
      To: 80
    - Label: https
      Value: 443
      To: 443
    - Label: ts_http
      Value: 80
      To: 80
      HostNetwork: tailscale
    - Label: ts_https
      Value: 443
      To: 443
      HostNetwork: tailscale
    DynamicPorts:
    - Label: health
      HostNetwork: hashinet
  Services:
  - Name: caddy
    PortLabel: health
    Checks:
    - Name: Health
      PortLabel: health
      Type: http
      Path: "/health"
      Interval: 60000000000
      Timeout: 10000000000
  RestartPolicy:
    Attempts: 5
    Interval: 1800000000000 # 30m
    Delay: 300000000000 # 5m
    Mode: delay # Try restart after ``interval`` time
```

### Logs
```
2022-10-18T15:04:08Z  Setup Failure  failed to setup alloc: pre-run hook "network" failed: failed to configure networking for alloc: failed to configure network: plugin type="bridge" failed (add): failed to allocate for range 0: 172.26.65.37 has been allocated to c31f3174-7c95-6c1e-d782-ea00579f84c3, duplicate allocation is not allowed
```
Note that the alloc id present here is the same as alloc for which I queried this logs.
