### ISSUE TITLE
${NOMAD_TASK_DIR} value not rendered in template body

### ISSUE THREAD

**Issue by sssilver** [hashicorp/nomad#15468]
### Nomad version
Nomad v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

### Operating system and Environment details
Ubuntu 22.04.1 LTS
Linux ironforge 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Issue
It looks like `${NOMAD_TASK_DIR}` is not being rendered in my job template:
```hcl
...
      template {
        destination = "${NOMAD_TASK_DIR}/config.yaml"
        change_mode = "restart"
        data = <<EOH
tunnel: f562a054-f138-4667-8799-3f5f9e996eae
credentials-file: ${NOMAD_TASK_DIR}/ironforge-credentials.json  # <------ Referencing the variable, expecting it to be substituted

metrics: :5000
no-autoupdate: true
warp-routing:
  enabled: true
ingress:
{{- range nomadService "hello" }}
- service: http://{{ .Address }}:{{ .Port }}
  hostname: ironforge.x17.space
{{- end }}

- service: http_status:404
EOH
      }

```

Here's the rendered template:

```
λ ~/projects/ironforge/ nomad alloc fs be37f4e6 cloudflared/local/config.yaml
tunnel: f562a054-f138-4667-8799-3f5f9e996eae
credentials-file: ${NOMAD_TASK_DIR}/ironforge-credentials.json  <-------- NOTICE: Templated value not rendered!!

metrics: :5000
no-autoupdate: true
warp-routing:
  enabled: true
ingress:
- service: http://192.168.86.36:26308
  hostname: ironforge.x17.space

- service: http_status:404
```

Am I missing something, or is this a bug?

### Reproduction steps
- Create a job with a template stanza that references `${NOMAD_TASK_DIR}` in `data`
- Run the job
- Observe that the rendered template does not substitute the `${NOMAD_TASK_DIR}` value

#### Expected Result
-  `${NOMAD_TASK_DIR}` value is properly rendered from the template into the final file

**Comment by krundru** [comment]
template follows `{{ env "NOMAD_TASK_DIR" }}` syntax. 

For example, this is how we are rendering part of envoy yaml file 
```
  - name: xds_cluster
    type: STATIC
    connect_timeout: 10s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: {{ env "attr.unique.network.ip-address" }}
                port_value: 5678
```
