### ISSUE TITLE
"Missing drivers" error when running jobs with nomad in docker containers

### ISSUE THREAD

**Issue by sronsiek** [hashicorp/nomad#1856]
Hi,

I'm running consul (0.7.0) + nomad client (0.4.1) + nomad server (0.4.1), each in separate docker containers on a cluster of 3 physical Linux hosts. 

`nomad server-members` run in the server container looks good:
```
Name           Address        Port  Status  Leader  Protocol  Build  Datacenter  Region
swarm1.europe  192.168.100.1  4648  alive   true    2         0.4.1  dc1         europe
swarm2.europe  192.168.100.2  4648  alive   false   2         0.4.1  if_da       europe
swarm3.europe  192.168.100.3  4648  alive   false   2         0.4.1  if_da       europe
```
The docker socket file  `/var/run/docker.sock` is mounted in the nomad containers, and the nomad containers are run by user nomad, whose primary group matches that of the socket file, which has group `rw` perms.

The nomad configs are listed below.

I have tried running a simple test job, that should launch simple docker container 'endless_loop'
in datacenter 'dc1', but it fails with:

`       * Constraint "missing drivers" filtered 1 nodes`

```
job "first_job" {
  region = "europe"
  datacenters = ["dc1"]
  type = "service"

  group "common" {
    count = 1
    task "test_task" {
      driver = "docker"
      config {
        image = "endless_loop:latest"
      }

      resources {
        cpu = 500 # 500 Mhz
        memory = 256 # 256MB
        }
      }
    }
  }
}
```

I also tried a job using the exec driver from [Issue #430](https://github.com/hashicorp/nomad/issues/430) (with typos corrected) and get the same error message as in the first job.

Nomad client & server share the following base config:

```
# Name the region, if omitted, the default "global" region will be used.
region = "europe"

# Persist data to a location that will survive a machine reboot.
data_dir = "/tmp/nomad/"

# Don't access internet for update checks:
disable_update_check = 1

# Bind to all addresses so that the Nomad agent is available both on loopback
# and externally.
# bind_addr = "0.0.0.0"
# For host networking (network_mode: "host") in yml:
bind_addr = "192.168.100.1"

# Advertise an accessible IP address so the server is reachable by other servers
# and clients. The IPs can be materialized by Terraform or be replaced by an
# init script.

consul {
    # Consul's HTTP Address
    address = "192.168.100.1:8500"
}

# Enable debug endpoints.
enable_debug = true

```

Nomad Server hcl:

```
# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "/tmp/server1"

# Advertise an accessible IP address so the server is reachable by other servers
# and clients.
advertise {
    http = "192.168.100.1:4646"
    rpc  = "192.168.100.1:4647"
    serf = "192.168.100.1:4648"
}

# Enable the server
server {
    enabled = true

    # Self-elect = 1, should be 3 or 5 for production
    bootstrap_expect = 3
}
```

Nomad Client hcl:

```
datacenter = "dc1"

# Increase log verbosity
log_level = "DEBUG"

# Setup data dir
data_dir = "/tmp/client1"

# Enable the client
client {
    enabled = true

    # For demo assume we are talking to server1. For production,
    # this should be like "nomad.service.consul:4647" and a system
    # like Consul used for service discovery.
    # servers = ["127.0.0.1:4647"]
    # The following line assumes use on consul dns is set up:
    # servers = ["nomad.service.consul:4647"]
    servers = ["192.168.100.1:4647"]
    network_interface = "eth0"
}

# Modify our port to avoid a collision with server1
ports {
    http = 5656
}
```

Nomad client & server containers are run using the following docker-compose file:

```
version: "2"
services:
  nomad-server:
    image: "sles12sp1-nomad:0.4.1"
    container_name: "nomad-server1"
    network_mode: "host"
    user: nomad:${DOCKER_GRP}
    volumes:
      - $PWD/nomad-base.hcl:/tmp/nomad-base.hcl
      - $PWD/nomad-server.hcl:/tmp/nomad-server.hcl
      - $PWD/variables.tf:/tmp/variables.tf
      # Totally temporarily, pwd to /opt for job access:
      - $PWD:/opt
      - /var/run/docker.sock:/var/run/docker.sock
    command: "agent -network-interface eth0 -config /tmp/nomad-base.hcl -config /tmp/nomad-server.hcl"

    # Need the following for cli to work without -address arg:
    environment:
      - "NOMAD_ADDR=http://${HOST_IP}:4646"

  nomad-client:
    image: "sles12sp1-nomad:0.4.1"
    container_name: "nomad-client1"
    # https://github.com/hashicorp/nomad/issues/542
    network_mode: "host"
    user: nomad:${DOCKER_GRP}
    volumes:
      - $PWD/nomad-base.hcl:/tmp/nomad-base.hcl
      - $PWD/nomad-client.hcl:/tmp/nomad-client.hcl
      - $PWD/variables.tf:/tmp/variables.tf
      # Totally temporarily, pwd to /opt for job access:
      - $PWD:/opt
    command: "agent -network-interface eth0 -config /tmp/nomad-base.hcl -config /tmp/nomad-client.hcl"

    # Need the following for cli to work without -address arg:
    environment:
      - "NOMAD_ADDR=http://${HOST_IP}:4646"

    depends_on:
      - nomad-server
```

Is there something obvious we're missing?
