### ISSUE TITLE
Some deployments disappear after Nomad servers restart

### ISSUE THREAD

**Issue by scor2k** [hashicorp/nomad#20270]
### Nomad version
Output from `nomad version`

```
nomad -version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc
```

### Operating system and Environment details

```
# cat /etc/*release*
Rocky Linux release 8.9 (Green Obsidian)
```

### Issue

Some jobs lost their deployments after the Nomad cluster restarted. It has happened on the older versions as well, cannot confirm that issue for 1.7.6 yet (upgrade in progress).

It looks like this in the CLI output:

```
$ /opt/nomad/current/nomad job status -namespace "*" application
ID            = application
Name          = application
Submit Date   = 2024-04-02T15:04:57Z
Type          = service
Priority      = 50
Datacenters   = staging
Namespace     = stage
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group                              Queued  Starting  Running  Failed  Complete  Lost  Unknown
application                              0       0         1        30      24        0     0
application-ingress                0       0         0        1       21        0     0

Allocations
ID        Node ID   Task Group                      Version  Desired  Status   Created   Modified
50831ec4  e0300762  application  96       run      running  2h8m ago  2h7m ago
```

There is no "Latest Deployment" section in the output but I see it for other jobs. 

### Reproduction steps

There are no exact steps to reproduce because not 100% of jobs lost their deployments. But we did a rolling restart this time:

```
staging-cp-01:
       Active: active (running) since Wed 2024-04-03 10:06:18 UTC; 2h 13min ago
staging-cp-02:
       Active: active (running) since Wed 2024-04-03 10:07:05 UTC; 2h 13min ago
staging-cp-03:
       Active: active (running) since Wed 2024-04-03 10:05:36 UTC; 2h 14min ago
```

#### Expected Result

Information about the latest deployment stays forever. 

### Other

I can provide Nomad logs, but there is no information about the job and deployments, only messages about restart. I'll be happy to hear some tips and tricks.
