### ISSUE TITLE
Allocation Metrics no longer emitted

### ISSUE THREAD

**Issue by dosera** [hashicorp/nomad#24339]
### Nomad version
```
Nomad v1.9.1
BuildDate 2024-10-21T09:00:50Z
Revision d9ec23f0c1035401e9df6c64d6ffb8bffc555a5e
```

### Operating system and Environment details
`AlmaLinux release 9.4 (Seafoam Ocelot)`

`/etc/nomad/base.hcl`:

```
telemetry {
..
  prometheus_metrics = "true"
  publish_allocation_metrics = "true"
  publish_node_metrics = "true"

..
}
```

### Issue
After upgrading nomad from `1.8.4` to `1.9.1` allocation metrics like `nomad_client_allocs_memory_usage` appear not to be properly emitted (or only for several seconds - i am using prometheus to scrape them).

### Reproduction steps
1. Enable telemetry
2. Start any allocation
3. Collect metrics

#### Expected Result
Allocation metrics are available.

#### Actual Result
Allocation metrics are available sporadically (at best). See the attached screenshot - nomad was upgraded on Oct 24th.

This is how it looks in prometheus since then:
![nomad no alloc metrics](https://github.com/user-attachments/assets/e17688bf-52e5-45af-a1dc-95f5958760c4)

**Comment by Himura2la** [comment]
We have the same issue with allocation metrics after updating from 1.8 to 1.9:
![image](https://github.com/user-attachments/assets/36ec3798-2456-422e-91d7-61dadbdd7ed9)
query: `avg_over_time(nomad_client_allocs_memory_usage[10m]) / avg_over_time(nomad_client_allocs_memory_allocated[10m])`

They are returned irregularly, and often values are zero.

our configs:
```hcl
telemetry {
  collection_interval = "30s"
  disable_hostname = true
  prometheus_metrics = true
  publish_allocation_metrics = true
  publish_node_metrics = true
}
```

```yml
global:
  scrape_interval:     1m
  scrape_timeout:     20s
  evaluation_interval: 1m

  - job_name: nomad
    static_configs:
      - targets:
        # ...
    scheme: https
    metrics_path: /v1/metrics
    params:
      format: [prometheus]
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

```
