### ISSUE TITLE
Template Stanza single quote and HCL2 cause parser error

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/nomad#9838]
Nomad 1.0.2

### Issue
We make pretty extensive usage of file content rendering in our template stanza's but we have noticed that if the file contents have ```''``` in them then the HCL renderer gives us this kind of message

```
Invalid character; Single quotes are not valid. Use double quotes (") to enclose strings.
```

The problem is that if we then replace the ```''``` in the file with ```""``` we then get a different error because we also have ```}``` and that error is

```
Extra characters after interpolation expression; Expected a closing brace to end the interpolation expression, but found extra characters
```

Here's a snippet from the job file
```
template {
        data = <<EOH
        [[ fileContents ( print .service_dir "/journalbeat.yml" ) ]]
        EOH

        destination = "local/journalbeat.yml"
      }
```

and the respective file it's trying loading in (redacted)
```
############################# Journalbeat #####################################

---
journalbeat.inputs:
  - paths: []
    include_matches:
      - "systemd.unit=vault.service"
    seek: cursor
    fields_under_root: true
    fields:
      type: control-plane-vault
      token: ${LOGZIO_TOKEN:''}
      logzio_codec: plain
      ipAddress: ${IP_ADDRESS:''}
      hostName: ${HOSTNAME:''}
      clusterName: ${CLUSTER_NAME:''}
      deploymentType: ${DEPLOYMENT_TYPE:''}
```
and with the single quote replacement
```
############################# Journalbeat #####################################

---
journalbeat.inputs:
  - paths: []
    include_matches:
      - "systemd.unit=vault.service"
    seek: cursor
    fields_under_root: true
    fields:
      type: control-plane-vault
      token: ${LOGZIO_TOKEN:""}
      logzio_codec: plain
      ipAddress: ${IP_ADDRESS:""}
      hostName: ${HOSTNAME:""}
      clusterName: ${CLUSTER_NAME:""}
      deploymentType: ${DEPLOYMENT_TYPE:""}
```

Neither of which are ok in the HCL2 parser.  However, if we run this with the ```-hcl1``` flag for deployment then it all works as expected
