### ISSUE TITLE
Sharing Volumes between containers

### ISSUE THREAD

**Issue by sikishen** [hashicorp/nomad#9910]
Hi there,

I want to use a sidecar container for sharing log directory and log rotate methods, but i couldn't see any way to share container volumes without by manually mounting them on the host https://www.nomadproject.io/docs/job-specification/volume, is it possible to share container volumes like docker-compose where i can simply do like this?

```
services:
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        links:
            - php
        volumes:
            - app-volume: /app-log

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - app-volume: /app-log

volumes:
     app-volume: 
```

Best Regards,
Siki.
